language: node_js

node_js: 
  - "8"

cache:
  directories:
    - node_modules

before_install:
  - "npm i"
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"

after_script:
  - npm run build
  - ls
  - git init
  - git add .
  - git commit -m "travis building"
  - git push --force --quiet "https://${G_TOKEN}@${G_PATH}" master:${G_BRANCH}

branches:
  only:
    - master
