language: node_js

node_js: 
  - "8"

cache:
  directories:
    - node_modules

before_install:
  - "npm i"

after_script:
  - npm run build
  - git init
  - git config user.name "rossroma"
  - git config user.email "906580223@qq.com"
  - git add .
  - git commit -m "travis building"
  - git push --force "https://${G_TOKEN}@github.com/rossroma/dinner.git" master:master

branches:
  only:
    - master

env:
 global: